### ISSUE TITLE
Inquiry for parameters setting

### ISSUE THREAD

**Issue by hefengxiyulu** [wangjie6866/CSGIS-Net#3]

**Comment by wangjie6866** [comment]
Just the folder name of the output file.
Thanks
















At 2022-12-10 13:08:45, "Wonshington" ***@***.***> wrote:

I have read this paper and am very interested in this work.
Thanks for your code. It is very useful for me, but I have some questions about parameter settings and would like to ask you.
In “python show.py --modelPath MODEL_PATH --test_dir TEST_PATH --sessname YOUR_SESSNAME --net HDC_edge_refine ”, what does “sessname” mean and how to set it(YOUR_SESSNAME)?
Look forward to your kind reply.
Thank you.
